steps:
- name: 'gcr.io/cloud-builders/docker'
  args: [
    'build',
    '--no-cache',
    '-t', 'gcr.io/nexa-teste-1/nexa-backend:latest',
    '.'
  ]
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/nexa-teste-1/nexa-backend:latest']
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: 'gcloud'
  args: [
    'run', 'deploy', 'nexa-backend-prod',
    '--image', 'gcr.io/nexa-teste-1/nexa-backend:latest',
    '--region', 'southamerica-east1',
    '--platform', 'managed',
    '--allow-unauthenticated',
    '--update-env-vars',
    'APP_ENV=production,APP_DEBUG=true,OTP_DEBUG=true,MAIL_MAILER=log,MAIL_HOST=127.0.0.1,MAIL_PORT=2525,MAIL_USERNAME=null,MAIL_PASSWORD=null,MAIL_ENCRYPTION=null,AWS_ACCESS_KEY_ID=dummy,AWS_SECRET_ACCESS_KEY=dummy,BROADCAST_DRIVER=reverb,REVERB_APP_KEY=nexa_reverb_key,REVERB_APP_SECRET=nexa_reverb_secret,REVERB_APP_ID=123456,REVERB_HOST=chat-prod-1044548850970.southamerica-east1.run.app,REVERB_PORT=443,REVERB_SCHEME=https,FILESYSTEM_DISK=gcs,GOOGLE_CLOUD_PROJECT_ID=nexa-teste-1,GOOGLE_CLOUD_STORAGE_BUCKET=nexa-uploads-prod'
  ]
images:
- 'gcr.io/nexa-teste-1/nexa-backend:latest'
